### ISSUE TITLE
Which dataset is DSST compatible with?

### ISSUE THREAD

**Issue by y22ma** [gnebehay/VOTR#1]
Hi,

Trying to setup DSST to run the tracker, but I'm having a hardtime finding a dataset that works with the setup and instructions on how to run against it. 

Just wondering if you could provide any links and instructions??

Cheers

**Comment by gnebehay** [comment]
DSST expects the input format to be x1,y1,x2,y2,x3,y3,x4,y4 which allows for rotated rectangles as input. I suspect that your input data is of the form x1,y1,w,h so you would have to perform a conversion first.

**Comment by gnebehay** [comment]
Sorry, my last comment was wrong, DSST supports both input types. The actual problem is that DSST is following the calling convention of the VOT challenge, so you need a script that prepares the input data to follow this convention. I will hopefully soon be able to upload a python script that does that for you.

**Comment by gnebehay** [comment]
I just pushed 5c16b99cdf4dcc1bd72d2fb21abf95b5407893e5 which might be interesting for you.
